server:
  port: ${BACKEND_SERVER_PORT}

application:
  values:
    authorization-header: authorization

spring:
  datasource:
    url: jdbc:${DATABASE}://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: ${DATABASE_DRIVER}
  jpa:
    open-in-view: false
#    generate-ddl: true
    generate-ddl: false
    show-sql: true
#    show-sql: false
    hibernate:
      ddl-auto: validate
#      ddl-auto: create
      properties:
        hibernate:
          format_sql: true
      database: ${DATABASE}
      database-platform: ${DATABASE_PLATFORM}
  liquibase:
    enabled: true
#    enabled: false
    change-log: liquibase/com/kalachinski/rpa/changelog.xml
    url: jdbc:${DATABASE}://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    user: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    queues:
      scan-db-message: ${SCAN_DB_MESSAGE}
      answer-message: ${ANSWER_MESSAGE}
      text-message: ${TEXT_MESSAGE}
      mail-service-message: ${MAIL_SERVICE_MESSAGE}

bot:
  token: ${BOT_TOKEN}
  name: ${BOT_NAME}

security:
  jwt:
    token:
      secret-key: ${SECURITY_JWT_TOKEN_CLIENT_SECRET}
      expiration-in-minutes: ${SECURITY_JWT_TOKEN_EXPIRATION}
      refresh-token:
        expiration-in-minutes: ${SECURITY_JWT_REFRESH_TOKEN_EXPIRATION}

springdoc:
  swagger-ui:
    enabled: ${SPRINGDOC_SWAGGERUI_ENABLED}
  use-management-port: true

management:
  server:
    port: ${OPENAPI_MANAGEMENT_SERVER_PORT}
  endpoints:
    web:
      exposure:
        include: openapi, swaggerui