server:
  port: ${BACKEND_SERVER_PORT}



application:
  values:
    authorization-header: authorization

spring:
  datasource:
    url: jdbc:${DATABASE}://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: ${DATABASE_DRIVER}
  jpa:
    open-in-view: false
    #    generate-ddl: true
#    show-sql: true
#    hibernate:
#      ddl-auto: create
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
      properties:
        hibernate:
          format_sql: true
      database: ${DATABASE}
      database-platform: ${DATABASE_PLATFORM}
  liquibase:
    enabled: true
#    enabled: false
    change-log: liquibase/com/kalachinski/rpa/changelog.xml
    url: jdbc:${DATABASE}://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    user: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

security:
  jwt:
    token:
      secret-key: ${SECURITY_JWT_TOKEN_CLIENT_SECRET}
      expiration-in-minutes: ${SECURITY_JWT_TOKEN_EXPIRATION}
      refresh-token:
        expiration-in-minutes: ${SECURITY_JWT_REFRESH_TOKEN_EXPIRATION}

springdoc:
  swagger-ui:
    enabled: ${SPRINGDOC_SWAGGERUI_ENABLED}
  use-management-port: true

management:
  server:
    port: ${OPENAPI_MANAGEMENT_SERVER_PORT}
  endpoints:
    web:
      exposure:
        include: openapi, swaggerui