server:
  port: ${BACKEND_SERVER_PORT}

spring:
  datasource:
    url: jdbc:${DATABASE}://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: ${DATABASE_DRIVER}
  jpa:
#    generate-ddl: true
#    show-sql: true
#    hibernate:
#      ddl-auto: create
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
#    enabled: false
    change-log: liquibase/com/kalachinski/rpa/changelog.xml
    url: jdbc:${DATABASE}://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    user: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}