server:
  port: 9000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rpa
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: liquibase/com/kalachinski/rpa/changelog.xml
    url: jdbc:postgresql://localhost:5432/rpa
    user: postgres
    password: postgres