server:
  port: ${SERVER_PORT}

spring:
  datasource:
    url: jdbc:${DATABASE}://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: none
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    queues:
      scan-db-message: ${SCAN_DB_MESSAGE}